akka {
  loglevel = "INFO"
  actor {
    provider = cluster
    serialization-bindings {
      "eu.example.ishare.common.protocol.ArProtocol$ArCommand" = jackson-cbor
      "eu.example.ishare.common.protocol.ManagementProtocol$ManagementCommand" = jackson-cbor
      "eu.example.ishare.common.protocol.VcProtocol$IssuerCommand" = jackson-cbor
      "eu.example.ishare.common.protocol.VcProtocol$WalletCommand" = jackson-cbor
    }
  }
  remote.artery {
    canonical.hostname = "127.0.0.1"
    canonical.port = 25251
  }
  cluster {
    seed-nodes = ["akka://ishare-cluster@127.0.0.1:25251"]
    min-nr-of-members = 1
  }
}
