edc.participant.id=EU.EORI.NLTESTCONSUMER
ishare.party.id=EU.EORI.NLTESTCONSUMER
ishare.vault.private.key=consumer-private-key
ishare.vault.certificate=consumer-certificate
ishare.pr.base.url=http://192.168.77.128:8081
ishare.pr.eori=EU.EORI.NLTESTPR
ishare.ar.base.url=http://localhost:7000
ishare.ar.eori=EU.EORI.NLTESTAR
web.http.management.port=29193
web.http.management.path=/management
web.http.protocol.port=29194
web.http.protocol.path=/protocol
web.http.control.port=29192
web.http.control.path=/control
web.http.port=29191
web.http.path=/api
edc.dsp.callback.address=http://localhost:29194/protocol
edc.dpf.selector.url=http://localhost:29192/control/v1/dataplanes
edc.keystore=resources/certs/consumer.p12
edc.keystore.password=changeit
edc.dataplane.api.public.baseurl=http://localhost:29291/public
web.http.public.port=29291
web.http.public.path=/public

ishare.bench.port=29199

edc.negotiation.state-machine.iteration-wait-millis=10
edc.transfer.state-machine.iteration-wait-millis=10
edc.dataplane.state-machine.iteration-wait-millis=10

ishare.ar.enforce=false

ishare.akka.host=127.0.0.1
ishare.akka.port=25252
ishare.akka.seed-nodes=akka://ishare-cluster@127.0.0.1:25251
ishare.ar.akka.ask-timeout-seconds=10
ishare.ar.akka.discovery-timeout-seconds=30
ishare.management.bridge.role=consumer
